-- 0006_supabase_auth_cutover.sql
--
-- Hand-authored (NOT generated by drizzle-kit): the drizzle journal and
-- supabase/migrations/meta/* are left untouched so `npm run db:check` stays
-- green. Promotes the spike artefacts under
-- docs/phase-1/05-tech-spikes/supabase-auth/ into the real migration for the
-- Auth.js -> Supabase Auth cut-over (issue #79, ADR-018, ADR-019).
--
-- NAMING DIVERGENCE (ADR-018 "profiles" vs the real table).
--   ADR-018 names "public.profiles" as the 1:1 anchor to auth.users.id. The
--   shipped schema has NO table called "profiles": the anchor is public.users
--   (uuid PK), with per-role detail in parent_profile / staff_profile /
--   student_profile (each FK'd to users.id). This migration targets the REAL
--   table (public.users) and reuses auth.users.id as the PK, so every
--   downstream FK (user_role.user_id, *_profile.user_id, family_link,
--   parent_verification_request.user_id, audit actor columns) survives with no
--   data migration, exactly as ADR-018 requires. "profiles" is treated as the
--   logical/ERD label for public.users; no rename is performed.
--
-- The users."emailVerified" column (Auth.js adapter camelCase, quoted in DDL)
-- is KEPT, not migrated: it is harmless, the provisioning trigger populates it
-- from auth.users.email_confirmed_at, and dropping it would churn FKs/snapshots
-- for no benefit.
--
-- DASHBOARD WIRING (performed by a human at turn-on, NOT by this migration):
--   1. Register public.add_rbac_claims as the custom access-token hook
--      (Authentication > Hooks > Customize Access Token).
--   2. Set the access-token (JWT) TTL to 5-15 min (Authentication > Sessions).
--   3. Enable the Google OAuth provider and its redirect URLs.
-- 0001_rls_policies.sql is UNCHANGED and stays correct-but-bypassed in v1
-- (service-role connection); this migration does NOT light up RLS.

-- ---------------------------------------------------------------------------
-- 1. auth.users -> public.users provisioning trigger (ADR-018)
-- ---------------------------------------------------------------------------
create or replace function public.provision_app_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.users (id, email, name, "emailVerified", created_at, updated_at)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'name', new.raw_user_meta_data ->> 'full_name'),
    new.email_confirmed_at,
    now(),
    now()
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
  after insert on auth.users
  for each row
  execute function public.provision_app_user();

-- ---------------------------------------------------------------------------
-- 2. Custom access-token hook: lightweight RBAC claims (ADR-019)
--    Injects role_codes, status, dept_ids into the JWT app_metadata. The full
--    permission catalogue is NOT in the token; the app resolves permissions per
--    request via loadSessionContext, which stays the source of truth. Column
--    references mirror src/lib/rbac/session-context.ts (snake_case DB columns).
-- ---------------------------------------------------------------------------
create or replace function public.add_rbac_claims(event jsonb)
returns jsonb
language plpgsql
stable
as $$
declare
  v_user_id uuid := (event ->> 'user_id')::uuid;
  v_role_codes text[];
  v_dept_ids text[];
  v_status text;
  v_is_parent boolean;
  v_latest_status text;
  v_claims jsonb;
begin
  select coalesce(array_agg(distinct r.code), '{}')
  into v_role_codes
  from public.user_role ur
  join public.roles r on r.id = ur.role_id
  where ur.user_id = v_user_id;

  select coalesce(array_agg(distinct d), '{}')
  into v_dept_ids
  from (
    select sp.dept_id::text as d
    from public.staff_profile sp
    where sp.user_id = v_user_id
      and sp.dept_id is not null
    union
    select ur.scope_id::text as d
    from public.user_role ur
    where ur.user_id = v_user_id
      and ur.scope_type = 'department'
  ) depts;

  v_is_parent := 'parent' = any(v_role_codes);

  if not v_is_parent then
    v_status := 'ACTIVE';
  else
    select pvr.status
    into v_latest_status
    from public.parent_verification_request pvr
    where pvr.user_id = v_user_id
    order by pvr.created_at desc
    limit 1;

    v_status := case
      when v_latest_status is null then 'ACTIVE'
      when v_latest_status = 'approved' then 'ACTIVE'
      when v_latest_status = 'rejected' then 'SUSPENDED'
      else 'PENDING_VERIFICATION'
    end;
  end if;

  v_claims := coalesce(event -> 'claims', '{}'::jsonb);

  v_claims := jsonb_set(
    v_claims,
    '{app_metadata}',
    coalesce(v_claims -> 'app_metadata', '{}'::jsonb)
      || jsonb_build_object(
        'role_codes', to_jsonb(v_role_codes),
        'status', to_jsonb(v_status),
        'dept_ids', to_jsonb(v_dept_ids)
      )
  );

  return jsonb_set(event, '{claims}', v_claims);
end;
$$;

grant execute on function public.add_rbac_claims(jsonb) to supabase_auth_admin;
grant usage on schema public to supabase_auth_admin;
grant select on
  public.user_role,
  public.roles,
  public.staff_profile,
  public.parent_verification_request
to supabase_auth_admin;

-- ---------------------------------------------------------------------------
-- 3. Drop the Auth.js adapter tables (ADR-018). public.users survives.
-- ---------------------------------------------------------------------------
drop table if exists "authenticators";
drop table if exists "accounts";
drop table if exists "sessions";
drop table if exists "verification_token";
